version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=timeManagement
      - MYSQL_HOST=mysqldb
    ports:
      - 3307:3306

  server:
    image: node-app:1.0
    depends_on:
      - mysqldb
    ports:
      - 3030:3030
    environment:
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=timeManagement
      - MYSQL_USER=root
